services:
  postgresql:
    image: postgres:latest
    container_name: postgresql
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
      - "8001:5432"
    networks:
      - app-network

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: backend
    ports:
      - "3000:3000"
    depends_on:
      - postgresql
    environment:
      - NODE_ENV=development
      - DATABASE_URL=postgresql://postgres:postgres@postgresql:5432/postgres
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
